### ISSUE TITLE
Need update to Phalcon 3.4.1 and PHP 7.2 extension for EA4

### ISSUE THREAD

**Issue by afbora** [CpanelInc/ea-scl-phalcon#1]
Need update to Phalcon 3.4.1 and PHP 7.2 extension for EA4

**Comment by afbora** [comment]
PHP 7.2 extension for EA4 didn't come for CloudLinux (up-to-date). Any idea?

![cl](https://user-images.githubusercontent.com/3393422/49448314-adcaf480-f7e9-11e8-9b4a-111abab47e24.jpeg)

**Comment by drmuey** [comment]
Cloudlinux has a seperate release cycle/YUM repositories.

For example, we did phalcon Nov 14:

https://documentation.cpanel.net/display/EA4/EasyApache+4+Change+Log+2018#EasyApache4ChangeLog2018-2018-11-14

I don't see it in theirs yet: https://www.cloudlinux.com/component/easyblog/tags/easyapache4

HTH!
