### ISSUE TITLE
Update to Phalcon 3.4.4 [with PHP 7.3]

### ISSUE THREAD

**Issue by zzpstudio** [CpanelInc/ea-scl-phalcon#5]
Hi
Can this be updated to use latest Phalcon version: 3.4.4 ?
See:
[blog.phalconphp.com/post/phalcon-3-4-4-released](https://blog.phalconphp.com/post/phalcon-3-4-4-released)

**Comment by gitloon** [comment]
Hello,
I've created EA-8571 on our backlog and barring any build and/or QA issues it should be included in an upcoming EA4 release.

**Comment by gitcory** [comment]
Hello,
I've created EA-8571 on our backlog and barring any build and/or QA issues it should be included in an upcoming EA4 release.
